export default {
  notfound: "/assets/images/404.svg",
  logo: "/vercel.svg",
  logo_img: "/assets/images/logo_img.png",
  banner_image: "/assets/images/banner_image.png",
  banner_back_image: "/assets/images/banner_back_image.png",
  icon1: "/assets/images/icon1.png",
  icon2: "/assets/images/icon2.png",
  icon3: "/assets/images/icon3.png",
  icon4: "/assets/images/icon4.png",
  icon5: "/assets/images/icon5.png",
  icon6: "/assets/images/icon6.png",
  home_products_bg: "/assets/images/home_products_bg.png",
  people_bg:"/assets/images/speak.png",
  social_icon1:"/assets/images/fb.png",
  social_icon2:"/assets/images/fb2.png",
  social_icon3:"/assets/images/fb3.png",
  social_icon4:"/assets/images/fb4.png",
  app_image1:"/assets/images/app.png",
  app_image2:"/assets/images/app1.png",
  footer_bg:"/assets/images/footer.jpg",
  ftr_logo:"/assets/images/ftr.png",
  country_bg:"/assets/images/us.png",
  map_image:"/assets/images/map.png",
  brand_image1:"/assets/images/bn1.png",
  brand_image2:"/assets/images/bn2.png",
  brand_image_bg:"/assets/images/bg2.png",
  test_bg:"/assets/images/test.png",
  quote:"/assets/images/cm.png",
  user:"/assets/images/cm2.jpg",
  top_arrow:"/assets/images/tp.png",
};
