export default {
  notfound: "/assets/images/404.svg",
  logo: "/vercel.svg",
  logo_img: "/assets/images/logo_img.png",
  banner_image: "/assets/images/banner_image.png",
  banner_back_image: "/assets/images/banner_back_image.png",
  icon1: "/assets/images/icon1.png",
  icon2: "/assets/images/icon2.png",
  icon3: "/assets/images/icon3.png",
  icon4: "/assets/images/icon4.png",
  icon5: "/assets/images/icon5.png",
  icon6: "/assets/images/icon6.png",
  home_products_bg: "/assets/images/home_products_bg.png",
  people_bg:"/assets/images/speak.png",
  social_icon1:"/assets/images/fb.png",
  social_icon2:"/assets/images/fb2.png",
  social_icon3:"/assets/images/fb3.png",
  social_icon4:"/assets/images/fb4.png",
  app_image1:"/assets/images/app.png",
  app_image2:"/assets/images/app1.png",
  footer_bg:"/assets/images/footer.jpg",
  ftr_logo:"/assets/images/ftr.png",
  country_bg:"/assets/images/us.png",
  map_image:"/assets/images/map.png",
  brand_image1:"/assets/images/bn1.png",
  brand_image2:"/assets/images/bn2.png",
  brand_image_bg:"/assets/images/bg2.png",
  test_bg:"/assets/images/test.png",
  quote:"/assets/images/cm.png",
  user:"/assets/images/cm2.jpg",
  top_arrow:"/assets/images/tp.png",
  inner_banner_bg:"/assets/images/inner_banner_bg.png",
  innerbanner1:"/assets/images/innerbanner1.png",
  tab1:"/assets/images/tab1.png",
  tab2:"/assets/images/tab2.png",
  tab3:"/assets/images/tab3.png",
  tab4:"/assets/images/tab4.png",
  tab5:"/assets/images/tab5.png",
  tab6:"/assets/images/tab6.png",
  tab_main_img1:"/assets/images/tab_main_img1.png",
  tab_main_img2:"/assets/images/tab_main_img2.png",
  stats_bg:"/assets/images/stats_bg.jpg",
  live_score_img:"/assets/images/live_score_img.png",
  live_stream_img:"/assets/images/live_stream_img.png",
  custom_set_img:"/assets/images/custom_set_img.png",
  scoreboard_img:"/assets/images/scoreboard_img.png"
};
